name: Build, test and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      env:
        FFLOGS_API_KEY: ${{ secrets.FFLOGS_API_KEY }}
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env:
        FFLOGS_API_KEY: ${{ secrets.FFLOGS_API_KEY }}
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: FFLogsAPI/bin/Release/FFLogsAPI.1.0.0.nupkg
        repo-owner: Shiroifuyu
        gh-user: Shiroifuyu
        token:  ${{ secrets.GITHUB_TOKEN }}
        skip-duplicate: true
